### ISSUE TITLE
Even if the database is populated, a restart does a full scan

### ISSUE THREAD

**Issue by dcardin** [fHDHR/fHDHR_plugin_origin_IPTVorg#8]
Which is super long for a list like United States...
Is that by design? Is there a quick way to say on a provider: don't scan on startup?
Thanks!

**Comment by deathbybandaid** [comment]
Going to point your attention at

https://github.com/fHDHR/fHDHR_plugin_origin_IPTVorg/blob/main/iptvorg_conf.json

I had designed a methodology to filter the channel listing.

I'll also point your attention to  `[fhdhr]chanscan_on_start = True` in the config listed in the advanced docs

**Comment by deathbybandaid** [comment]
side note, that was originally implemented when fHDHR used a single origin. This could easily be migrated to a per-origin setting

**Comment by dcardin** [comment]
The filtering works, with my modification. I haven't managed to do multiple filters yet, but that's because I never coded in python and I,m learning as I go along. but the chanscan_on_start is exactly what the doctor ordered :D thanks gain

**Comment by deathbybandaid** [comment]
I'm adding the above per-origin setting now

**Comment by deathbybandaid** [comment]
@dcardin https://github.com/fHDHR/fHDHR/pull/178
