### ISSUE TITLE
Crash on EPG cache update

### ISSUE THREAD

**Issue by dcardin** [fHDHR/fHDHR_plugin_origin_IPTVorg#9]
I have full logging on, there's not stack/exception...
Suggestions?

[2021-09-02 16:20:12,983] NOOB - Updating iptvorg EPG cache.
Killed

systematically.

**Comment by deathbybandaid** [comment]
Theoretically, it should return an empty programguide

https://github.com/fHDHR/fHDHR_plugin_origin_IPTVorg/blob/main/epg/__init__.py#L14

**Comment by deathbybandaid** [comment]
can you set the config `[logging]level=debug`?

**Comment by dcardin** [comment]
> can you set the config `[logging]level=debug`?
It is set to debug, that's why I was surprised to not see any message at all.

**Comment by deathbybandaid** [comment]
Odd, you should get a reason for a crash

**Comment by deathbybandaid** [comment]
https://github.com/fHDHR/fHDHR/pull/184

Try this core update, and see if that helps
